export const PHRASES = [
  {
    "id": 1,
    "track": "Everyday Arabic",
    "category": "Greetings",
    "level": "A1",
    "arabic": "السَّلَامُ عَلَيْكُمْ",
    "transliteration": "As-salāmu ʿalaykum",
    "english": "Peace be upon you",
    "answer": "peace be upon you",
    "notes": "A very common greeting."
  },
  {
    "id": 2,
    "track": "Everyday Arabic",
    "category": "Greetings",
    "level": "A1",
    "arabic": "صَبَاحُ الْخَيْرِ",
    "transliteration": "Ṣabāḥu al-khayr",
    "english": "Good morning",
    "answer": "good morning",
    "notes": "Used in daily conversation."
  },
  {
    "id": 3,
    "track": "Everyday Arabic",
    "category": "Greetings",
    "level": "A1",
    "arabic": "مَسَاءُ الْخَيْرِ",
    "transliteration": "Masāʾu al-khayr",
    "english": "Good evening",
    "answer": "good evening",
    "notes": "A common evening greeting."
  },
  {
    "id": 4,
    "track": "Everyday Arabic",
    "category": "Basics",
    "level": "A1",
    "arabic": "كَيْفَ حَالُكَ؟",
    "transliteration": "Kayfa ḥāluka?",
    "english": "How are you?",
    "answer": "how are you",
    "notes": "A simple everyday question."
  },
  {
    "id": 5,
    "track": "Everyday Arabic",
    "category": "Basics",
    "level": "A1",
    "arabic": "أَنَا بِخَيْرٍ",
    "transliteration": "Anā bikhayr",
    "english": "I am fine",
    "answer": "i am fine",
    "notes": "A common response."
  },
  {
    "id": 6,
    "track": "Everyday Arabic",
    "category": "Daily Life",
    "level": "A1",
    "arabic": "أُرِيدُ قَهْوَةً",
    "transliteration": "Urīdu qahwatan",
    "english": "I want coffee",
    "answer": "i want coffee",
    "notes": "Useful daily pattern."
  },
  {
    "id": 7,
    "track": "Everyday Arabic",
    "category": "Daily Life",
    "level": "A1",
    "arabic": "أَيْنَ الْمَاءُ؟",
    "transliteration": "Ayna al-māʾ?",
    "english": "Where is the water?",
    "answer": "where is the water",
    "notes": "Useful question form."
  },
  {
    "id": 8,
    "track": "Travel",
    "category": "Travel",
    "level": "A1",
    "arabic": "كَمْ هَذَا؟",
    "transliteration": "Kam hādhā?",
    "english": "How much is this?",
    "answer": "how much is this",
    "notes": "Useful for shopping."
  },
  {
    "id": 9,
    "track": "Travel",
    "category": "Travel",
    "level": "A1",
    "arabic": "أَيْنَ الْحَمَّامُ؟",
    "transliteration": "Ayna al-ḥammām?",
    "english": "Where is the bathroom?",
    "answer": "where is the bathroom",
    "notes": "Practical travel phrase."
  },
  {
    "id": 10,
    "track": "Everyday Arabic",
    "category": "Family",
    "level": "A1",
    "arabic": "هَذَا أَبِي",
    "transliteration": "Hādhā abī",
    "english": "This is my father",
    "answer": "this is my father",
    "notes": "Basic family expression."
  },
  {
    "id": 11,
    "track": "Everyday Arabic",
    "category": "Daily Life",
    "level": "A1",
    "arabic": "أَنَا جَاهِزٌ",
    "transliteration": "Anā jāhiz",
    "english": "I am ready",
    "answer": "i am ready",
    "notes": "Useful daily phrase."
  },
  {
    "id": 12,
    "track": "Everyday Arabic",
    "category": "Home",
    "level": "A1",
    "arabic": "اِفْتَحِ الْبَابَ",
    "transliteration": "Iftaḥ al-bāb",
    "english": "Open the door",
    "answer": "open the door",
    "notes": "Useful command form."
  },
  {
    "id": 13,
    "track": "Reading Arabic",
    "category": "News Words",
    "level": "A2",
    "arabic": "اِقْتِصَاد",
    "transliteration": "Iqtiṣād",
    "english": "Economy",
    "answer": "economy",
    "notes": "Very common in headlines."
  },
  {
    "id": 14,
    "track": "Reading Arabic",
    "category": "News Words",
    "level": "A2",
    "arabic": "حُكُومَة",
    "transliteration": "Ḥukūma",
    "english": "Government",
    "answer": "government",
    "notes": "Frequent in public affairs."
  },
  {
    "id": 15,
    "track": "Reading Arabic",
    "category": "News Words",
    "level": "A2",
    "arabic": "تَارِيخ",
    "transliteration": "Tārīkh",
    "english": "History",
    "answer": "history",
    "notes": "Useful reading word."
  },
  {
    "id": 16,
    "track": "Reading Arabic",
    "category": "Social Media",
    "level": "A2",
    "arabic": "مُهِمّ",
    "transliteration": "Muhimm",
    "english": "Important",
    "answer": "important",
    "notes": "Frequent modern usage."
  },
  {
    "id": 17,
    "track": "Reading Arabic",
    "category": "Social Media",
    "level": "A2",
    "arabic": "مُمْكِن",
    "transliteration": "Mumkin",
    "english": "Possible",
    "answer": "possible",
    "notes": "Frequent everyday word."
  },
  {
    "id": 18,
    "track": "Reading Arabic",
    "category": "Social Media",
    "level": "A2",
    "arabic": "فِكْرَة جَيِّدَة",
    "transliteration": "Fikra jayyida",
    "english": "A good idea",
    "answer": "a good idea",
    "notes": "Good for short opinion posts."
  },
  {
    "id": 19,
    "track": "Culture & Proverbs",
    "category": "Proverbs",
    "level": "B1",
    "arabic": "الصَّبْرُ مِفْتَاحُ الْفَرَجِ",
    "transliteration": "Aṣ-ṣabru miftāḥu al-faraj",
    "english": "Patience is the key to relief",
    "answer": "patience is the key to relief",
    "notes": "A classic proverb."
  },
  {
    "id": 20,
    "track": "Culture & Proverbs",
    "category": "Proverbs",
    "level": "B1",
    "arabic": "الْوَقْتُ مِنْ ذَهَبٍ",
    "transliteration": "Al-waqtu min dhahab",
    "english": "Time is gold",
    "answer": "time is gold",
    "notes": "Short, memorable proverb."
  },
  {
    "id": 21,
    "track": "Culture & Proverbs",
    "category": "Idioms",
    "level": "B1",
    "arabic": "فِي نَفْسِ الْوَقْتِ",
    "transliteration": "Fī nafs al-waqt",
    "english": "At the same time",
    "answer": "at the same time",
    "notes": "Useful reading connector."
  },
  {
    "id": 22,
    "track": "Culture & Proverbs",
    "category": "Idioms",
    "level": "B1",
    "arabic": "بَيْنَ يَدَيْكَ",
    "transliteration": "Bayna yadayk",
    "english": "In front of you",
    "answer": "in front of you",
    "notes": "Formal/literary usage."
  },
  {
    "id": 23,
    "track": "Reading Arabic",
    "category": "Light News",
    "level": "B1",
    "arabic": "أَعْلَنَتِ الشَّرِكَةُ مَشْرُوعًا جَدِيدًا",
    "transliteration": "Aʿlanat ash-sharika mashrūʿan jadīdan",
    "english": "The company announced a new project",
    "answer": "the company announced a new project",
    "notes": "Headline-style sentence."
  },
  {
    "id": 24,
    "track": "Reading Arabic",
    "category": "Light News",
    "level": "B1",
    "arabic": "شَهِدَتِ الْمَدِينَةُ أَحْدَاثًا مُهِمَّةً",
    "transliteration": "Shahidat al-madīna aḥdāthan muhimma",
    "english": "The city witnessed important events",
    "answer": "the city witnessed important events",
    "notes": "Closer to news prose."
  },
  {
    "id": 25,
    "track": "Everyday Arabic",
    "category": "Daily Life",
    "level": "A2",
    "arabic": "أُرِيدُ شَايًا",
    "transliteration": "Urīdu shāyan",
    "english": "I want tea",
    "answer": "i want tea",
    "notes": "Useful daily learning phrase."
  },
  {
    "id": 26,
    "track": "Everyday Arabic",
    "category": "Daily Life",
    "level": "A2",
    "arabic": "أُرِيدُ كِتَابًا",
    "transliteration": "Urīdu kitāban",
    "english": "I want a book",
    "answer": "i want a book",
    "notes": "Useful daily learning phrase."
  },
  {
    "id": 27,
    "track": "Everyday Arabic",
    "category": "Daily Life",
    "level": "A2",
    "arabic": "أُرِيدُ جَرِيدَةً",
    "transliteration": "Urīdu jarīdatan",
    "english": "I want a newspaper",
    "answer": "i want a newspaper",
    "notes": "Useful daily learning phrase."
  },
  {
    "id": 28,
    "track": "Everyday Arabic",
    "category": "Daily Life",
    "level": "A2",
    "arabic": "أُحِبُّ هَذَا الْمَكَانَ",
    "transliteration": "Uḥibbu hādhā al-makān",
    "english": "I like this place",
    "answer": "i like this place",
    "notes": "Useful daily learning phrase."
  },
  {
    "id": 29,
    "track": "Everyday Arabic",
    "category": "Daily Life",
    "level": "A2",
    "arabic": "هَذَا الْكِتَابُ مُفِيدٌ",
    "transliteration": "Hādhā al-kitābu mufīd",
    "english": "This book is useful",
    "answer": "this book is useful",
    "notes": "Useful daily learning phrase."
  },
  {
    "id": 30,
    "track": "Everyday Arabic",
    "category": "Daily Life",
    "level": "A2",
    "arabic": "الْجَوُّ جَمِيلٌ الْيَوْمَ",
    "transliteration": "Al-jawwu jamīl al-yawm",
    "english": "The weather is pleasant today",
    "answer": "the weather is pleasant today",
    "notes": "Useful daily learning phrase."
  },
  {
    "id": 31,
    "track": "Everyday Arabic",
    "category": "Daily Life",
    "level": "A2",
    "arabic": "أَحْتَاجُ إِلَى وَقْتٍ",
    "transliteration": "Aḥtāju ilā waqtin",
    "english": "I need time",
    "answer": "i need time",
    "notes": "Useful daily learning phrase."
  },
  {
    "id": 32,
    "track": "Everyday Arabic",
    "category": "Daily Life",
    "level": "A2",
    "arabic": "لَا أَفْهَمُ هَذِهِ الْكَلِمَةَ",
    "transliteration": "Lā afhamu hādhihi al-kalima",
    "english": "I do not understand this word",
    "answer": "i do not understand this word",
    "notes": "Useful daily learning phrase."
  },
  {
    "id": 33,
    "track": "Everyday Arabic",
    "category": "Daily Life",
    "level": "A2",
    "arabic": "أُرِيدُ أَنْ أَتَعَلَّمَ أَكْثَرَ",
    "transliteration": "Urīdu an ataʿallama akthar",
    "english": "I want to learn more",
    "answer": "i want to learn more",
    "notes": "Useful daily learning phrase."
  },
  {
    "id": 34,
    "track": "Everyday Arabic",
    "category": "Daily Life",
    "level": "A2",
    "arabic": "هَلْ يُمْكِنُ أَنْ تُعِيدَ ذَلِكَ؟",
    "transliteration": "Hal yumkinu an tuʿīda dhālika?",
    "english": "Can you repeat that?",
    "answer": "can you repeat that",
    "notes": "Useful daily learning phrase."
  },
  {
    "id": 35,
    "track": "Everyday Arabic",
    "category": "Daily Life",
    "level": "A2",
    "arabic": "هَذَا سَهْلٌ نِسْبِيًّا",
    "transliteration": "Hādhā sahlun nisbiyyan",
    "english": "This is relatively easy",
    "answer": "this is relatively easy",
    "notes": "Useful daily learning phrase."
  },
  {
    "id": 36,
    "track": "Everyday Arabic",
    "category": "Daily Life",
    "level": "A2",
    "arabic": "هَذَا أَصْعَبُ قَلِيلًا",
    "transliteration": "Hādhā aṣʿabu qalīlan",
    "english": "This is a little harder",
    "answer": "this is a little harder",
    "notes": "Useful daily learning phrase."
  },
  {
    "id": 37,
    "track": "Everyday Arabic",
    "category": "Daily Life",
    "level": "A2",
    "arabic": "أَقْرَأُ قَلِيلًا كُلَّ يَوْمٍ",
    "transliteration": "Aqraʾu qalīlan kulla yawm",
    "english": "I read a little every day",
    "answer": "i read a little every day",
    "notes": "Useful daily learning phrase."
  },
  {
    "id": 38,
    "track": "Everyday Arabic",
    "category": "Daily Life",
    "level": "A2",
    "arabic": "أَكْتُبُ الْكَلِمَاتِ الْجَدِيدَةَ",
    "transliteration": "Aktubu al-kalimāt al-jadīda",
    "english": "I write the new words",
    "answer": "i write the new words",
    "notes": "Useful daily learning phrase."
  },
  {
    "id": 39,
    "track": "Everyday Arabic",
    "category": "Daily Life",
    "level": "A2",
    "arabic": "أَسْتَمِعُ إِلَى النُّطْقِ بِبُطْءٍ",
    "transliteration": "Astamiʿu ilā an-nuṭqi bibuṭʾ",
    "english": "I listen to the pronunciation slowly",
    "answer": "i listen to the pronunciation slowly",
    "notes": "Useful daily learning phrase."
  },
  {
    "id": 40,
    "track": "Travel",
    "category": "Travel",
    "level": "A2",
    "arabic": "أَيْنَ الْمَحَطَّةُ؟",
    "transliteration": "Ayna al-maḥaṭṭa?",
    "english": "Where is the station?",
    "answer": "where is the station",
    "notes": "Useful for movement and directions."
  },
  {
    "id": 41,
    "track": "Travel",
    "category": "Travel",
    "level": "A2",
    "arabic": "مَتَى يَصِلُ الْقِطَارُ؟",
    "transliteration": "Matā yaṣilu al-qiṭār?",
    "english": "When does the train arrive?",
    "answer": "when does the train arrive",
    "notes": "Useful for movement and directions."
  },
  {
    "id": 42,
    "track": "Travel",
    "category": "Travel",
    "level": "A2",
    "arabic": "أُرِيدُ تَذْكِرَةً إِلَى الْمَدِينَةِ",
    "transliteration": "Urīdu tadhkiratan ilā al-madīna",
    "english": "I want a ticket to the city",
    "answer": "i want a ticket to the city",
    "notes": "Useful for movement and directions."
  },
  {
    "id": 43,
    "track": "Travel",
    "category": "Travel",
    "level": "A2",
    "arabic": "هَلْ هَذَا الطَّرِيقُ صَحِيحٌ؟",
    "transliteration": "Hal hādhā aṭ-ṭarīqu ṣaḥīḥ?",
    "english": "Is this the right way?",
    "answer": "is this the right way",
    "notes": "Useful for movement and directions."
  },
  {
    "id": 44,
    "track": "Travel",
    "category": "Travel",
    "level": "A2",
    "arabic": "أَيْنَ الْفُنْدُقُ؟",
    "transliteration": "Ayna al-funduq?",
    "english": "Where is the hotel?",
    "answer": "where is the hotel",
    "notes": "Useful for movement and directions."
  },
  {
    "id": 45,
    "track": "Travel",
    "category": "Travel",
    "level": "A2",
    "arabic": "أَيْنَ السُّوقُ الْقَدِيمُ؟",
    "transliteration": "Ayna as-sūqu al-qadīm?",
    "english": "Where is the old market?",
    "answer": "where is the old market",
    "notes": "Useful for movement and directions."
  },
  {
    "id": 46,
    "track": "Travel",
    "category": "Travel",
    "level": "A2",
    "arabic": "أُفَضِّلُ السَّفَرَ صَبَاحًا",
    "transliteration": "Ufaḍḍilu as-safara ṣabāḥan",
    "english": "I prefer to travel in the morning",
    "answer": "i prefer to travel in the morning",
    "notes": "Useful for movement and directions."
  },
  {
    "id": 47,
    "track": "Travel",
    "category": "Travel",
    "level": "A2",
    "arabic": "هَلْ هُنَاكَ مَتْحَفٌ قَرِيبٌ؟",
    "transliteration": "Hal hunāka mathafun qarīb?",
    "english": "Is there a museum nearby?",
    "answer": "is there a museum nearby",
    "notes": "Useful for movement and directions."
  },
  {
    "id": 48,
    "track": "Travel",
    "category": "Travel",
    "level": "A2",
    "arabic": "أَيْنَ يُمْكِنُنِي شِرَاءُ الْخَرِيطَةِ؟",
    "transliteration": "Ayna yumkinunī shirāʾu al-kharīṭa?",
    "english": "Where can I buy a map?",
    "answer": "where can i buy a map",
    "notes": "Useful for movement and directions."
  },
  {
    "id": 49,
    "track": "Travel",
    "category": "Travel",
    "level": "A2",
    "arabic": "أُرِيدُ أَنْ أَزُورَ الْمَكْتَبَةَ",
    "transliteration": "Urīdu an azūra al-maktaba",
    "english": "I want to visit the library",
    "answer": "i want to visit the library",
    "notes": "Useful for movement and directions."
  },
  {
    "id": 50,
    "track": "Travel",
    "category": "Travel",
    "level": "A2",
    "arabic": "هَذِهِ الْمِنْطَقَةُ هَادِئَةٌ",
    "transliteration": "Hādhihi al-minṭaqa hādiʾa",
    "english": "This area is quiet",
    "answer": "this area is quiet",
    "notes": "Useful for movement and directions."
  },
  {
    "id": 51,
    "track": "Travel",
    "category": "Travel",
    "level": "A2",
    "arabic": "الطَّرِيقُ مُزْدَحِمٌ هَذَا الْمَسَاءَ",
    "transliteration": "Aṭ-ṭarīqu muzdahim hādhā al-masāʾ",
    "english": "The road is crowded this evening",
    "answer": "the road is crowded this evening",
    "notes": "Useful for movement and directions."
  },
  {
    "id": 52,
    "track": "Everyday Arabic",
    "category": "Food & Drink",
    "level": "A2",
    "arabic": "أُفَضِّلُ الْخُبْزَ الطَّازَجَ",
    "transliteration": "Ufaḍḍilu al-khubza aṭ-ṭāzaj",
    "english": "I prefer fresh bread",
    "answer": "i prefer fresh bread",
    "notes": "Useful in cafés and meals."
  },
  {
    "id": 53,
    "track": "Everyday Arabic",
    "category": "Food & Drink",
    "level": "A2",
    "arabic": "هَلْ هَذَا الطَّعَامُ حَارٌّ؟",
    "transliteration": "Hal hādhā aṭ-ṭaʿāmu ḥārr?",
    "english": "Is this food spicy?",
    "answer": "is this food spicy",
    "notes": "Useful in cafés and meals."
  },
  {
    "id": 54,
    "track": "Everyday Arabic",
    "category": "Food & Drink",
    "level": "A2",
    "arabic": "أُرِيدُ كُوبًا مِنَ الْمَاءِ",
    "transliteration": "Urīdu kūban mina al-māʾ",
    "english": "I want a glass of water",
    "answer": "i want a glass of water",
    "notes": "Useful in cafés and meals."
  },
  {
    "id": 55,
    "track": "Everyday Arabic",
    "category": "Food & Drink",
    "level": "A2",
    "arabic": "هَذَا الشَّايُ لَذِيذٌ",
    "transliteration": "Hādhā ash-shāyu ladhīdh",
    "english": "This tea is delicious",
    "answer": "this tea is delicious",
    "notes": "Useful in cafés and meals."
  },
  {
    "id": 56,
    "track": "Everyday Arabic",
    "category": "Food & Drink",
    "level": "A2",
    "arabic": "مَا أَفْضَلُ طَبَقٍ هُنَا؟",
    "transliteration": "Mā afḍalu ṭabaqin hunā?",
    "english": "What is the best dish here?",
    "answer": "what is the best dish here",
    "notes": "Useful in cafés and meals."
  },
  {
    "id": 57,
    "track": "Everyday Arabic",
    "category": "Food & Drink",
    "level": "A2",
    "arabic": "السُّكَّرُ قَلِيلٌ فِي هَذَا",
    "transliteration": "As-sukkaru qalīlun fī hādhā",
    "english": "There is little sugar in this",
    "answer": "there is little sugar in this",
    "notes": "Useful in cafés and meals."
  },
  {
    "id": 58,
    "track": "Everyday Arabic",
    "category": "Food & Drink",
    "level": "A2",
    "arabic": "أُحِبُّ الْفَاكِهَةَ فِي الصَّبَاحِ",
    "transliteration": "Uḥibbu al-fākihata fī aṣ-ṣabāḥ",
    "english": "I like fruit in the morning",
    "answer": "i like fruit in the morning",
    "notes": "Useful in cafés and meals."
  },
  {
    "id": 59,
    "track": "Everyday Arabic",
    "category": "Food & Drink",
    "level": "A2",
    "arabic": "هَذِهِ الْقَهْوَةُ قَوِيَّةٌ",
    "transliteration": "Hādhihi al-qahwatu qawiyya",
    "english": "This coffee is strong",
    "answer": "this coffee is strong",
    "notes": "Useful in cafés and meals."
  },
  {
    "id": 60,
    "track": "Everyday Arabic",
    "category": "Food & Drink",
    "level": "A2",
    "arabic": "أُفَضِّلُ الطَّعَامَ الْبَسِيطَ",
    "transliteration": "Ufaḍḍilu aṭ-ṭaʿāma al-basīṭ",
    "english": "I prefer simple food",
    "answer": "i prefer simple food",
    "notes": "Useful in cafés and meals."
  },
  {
    "id": 61,
    "track": "Everyday Arabic",
    "category": "Food & Drink",
    "level": "A2",
    "arabic": "هَلْ يُمْكِنُ أَنْ تُحْضِرَ الْحِسَابَ؟",
    "transliteration": "Hal yumkinu an tuḥḍira al-ḥisāb?",
    "english": "Can you bring the bill?",
    "answer": "can you bring the bill",
    "notes": "Useful in cafés and meals."
  },
  {
    "id": 62,
    "track": "Reading Arabic",
    "category": "Core Reading Words",
    "level": "A2",
    "arabic": "مَقَال",
    "transliteration": "Maqāl",
    "english": "Article",
    "answer": "article",
    "notes": "High-frequency reading vocabulary."
  },
  {
    "id": 63,
    "track": "Reading Arabic",
    "category": "Core Reading Words",
    "level": "A2",
    "arabic": "خَبَر",
    "transliteration": "Khabar",
    "english": "News",
    "answer": "news",
    "notes": "High-frequency reading vocabulary."
  },
  {
    "id": 64,
    "track": "Reading Arabic",
    "category": "Core Reading Words",
    "level": "A2",
    "arabic": "رَأْي",
    "transliteration": "Raʾy",
    "english": "Opinion",
    "answer": "opinion",
    "notes": "High-frequency reading vocabulary."
  },
  {
    "id": 65,
    "track": "Reading Arabic",
    "category": "Core Reading Words",
    "level": "A2",
    "arabic": "نِقَاش",
    "transliteration": "Niqāsh",
    "english": "Discussion",
    "answer": "discussion",
    "notes": "High-frequency reading vocabulary."
  },
  {
    "id": 66,
    "track": "Reading Arabic",
    "category": "Core Reading Words",
    "level": "A2",
    "arabic": "تَحْلِيل",
    "transliteration": "Taḥlīl",
    "english": "Analysis",
    "answer": "analysis",
    "notes": "High-frequency reading vocabulary."
  },
  {
    "id": 67,
    "track": "Reading Arabic",
    "category": "Core Reading Words",
    "level": "A2",
    "arabic": "تَغْيِير",
    "transliteration": "Taghyīr",
    "english": "Change",
    "answer": "change",
    "notes": "High-frequency reading vocabulary."
  },
  {
    "id": 68,
    "track": "Reading Arabic",
    "category": "Core Reading Words",
    "level": "A2",
    "arabic": "مُجْتَمَع",
    "transliteration": "Mujtamaʿ",
    "english": "Society",
    "answer": "society",
    "notes": "High-frequency reading vocabulary."
  },
  {
    "id": 69,
    "track": "Reading Arabic",
    "category": "Core Reading Words",
    "level": "A2",
    "arabic": "ثَقَافَة",
    "transliteration": "Thaqāfa",
    "english": "Culture",
    "answer": "culture",
    "notes": "High-frequency reading vocabulary."
  },
  {
    "id": 70,
    "track": "Reading Arabic",
    "category": "Core Reading Words",
    "level": "A2",
    "arabic": "تَعْلِيم",
    "transliteration": "Taʿlīm",
    "english": "Education",
    "answer": "education",
    "notes": "High-frequency reading vocabulary."
  },
  {
    "id": 71,
    "track": "Reading Arabic",
    "category": "Core Reading Words",
    "level": "A2",
    "arabic": "لُغَة",
    "transliteration": "Lugha",
    "english": "Language",
    "answer": "language",
    "notes": "High-frequency reading vocabulary."
  },
  {
    "id": 72,
    "track": "Reading Arabic",
    "category": "Core Reading Words",
    "level": "A2",
    "arabic": "مَعْنًى",
    "transliteration": "Maʿnā",
    "english": "Meaning",
    "answer": "meaning",
    "notes": "High-frequency reading vocabulary."
  },
  {
    "id": 73,
    "track": "Reading Arabic",
    "category": "Core Reading Words",
    "level": "A2",
    "arabic": "فِكْر",
    "transliteration": "Fikr",
    "english": "Thought",
    "answer": "thought",
    "notes": "High-frequency reading vocabulary."
  },
  {
    "id": 74,
    "track": "Reading Arabic",
    "category": "Core Reading Words",
    "level": "A2",
    "arabic": "عَالَم",
    "transliteration": "ʿĀlam",
    "english": "World",
    "answer": "world",
    "notes": "High-frequency reading vocabulary."
  },
  {
    "id": 75,
    "track": "Reading Arabic",
    "category": "Core Reading Words",
    "level": "A2",
    "arabic": "مَدِينَة",
    "transliteration": "Madīna",
    "english": "City",
    "answer": "city",
    "notes": "High-frequency reading vocabulary."
  },
  {
    "id": 76,
    "track": "Reading Arabic",
    "category": "Core Reading Words",
    "level": "A2",
    "arabic": "قِرَاءَة",
    "transliteration": "Qirāʾa",
    "english": "Reading",
    "answer": "reading",
    "notes": "High-frequency reading vocabulary."
  },
  {
    "id": 77,
    "track": "Reading Arabic",
    "category": "Core Reading Words",
    "level": "A2",
    "arabic": "كِتَابَة",
    "transliteration": "Kitāba",
    "english": "Writing",
    "answer": "writing",
    "notes": "High-frequency reading vocabulary."
  },
  {
    "id": 78,
    "track": "Reading Arabic",
    "category": "Light News",
    "level": "B1",
    "arabic": "نَشَرَتِ الصَّحِيفَةُ تَقْرِيرًا جَدِيدًا",
    "transliteration": "Nasharat aṣ-ṣaḥīfatu taqrīran jadīdan",
    "english": "The newspaper published a new report",
    "answer": "the newspaper published a new report",
    "notes": "Useful for reading headlines and short reports."
  },
  {
    "id": 79,
    "track": "Reading Arabic",
    "category": "Light News",
    "level": "B1",
    "arabic": "أَثَارَ الْمَوْضُوعُ نِقَاشًا وَاسِعًا",
    "transliteration": "Athāra al-mawḍūʿu niqāshan wāsiʿan",
    "english": "The topic sparked broad discussion",
    "answer": "the topic sparked broad discussion",
    "notes": "Useful for reading headlines and short reports."
  },
  {
    "id": 80,
    "track": "Reading Arabic",
    "category": "Light News",
    "level": "B1",
    "arabic": "تَزَايَدَ الِاهْتِمَامُ بِالتَّعْلِيمِ الرَّقْمِيِّ",
    "transliteration": "Tazāyada al-ihtimāmu bi-t-taʿlīmi ar-raqamī",
    "english": "Interest in digital education increased",
    "answer": "interest in digital education increased",
    "notes": "Useful for reading headlines and short reports."
  },
  {
    "id": 81,
    "track": "Reading Arabic",
    "category": "Light News",
    "level": "B1",
    "arabic": "أَكَّدَ الْمَسْؤُولُ أَهَمِّيَّةَ الْحِوَارِ",
    "transliteration": "Akkada al-masʾūlu ahammiyyata al-ḥiwār",
    "english": "The official emphasized the importance of dialogue",
    "answer": "the official emphasized the importance of dialogue",
    "notes": "Useful for reading headlines and short reports."
  },
  {
    "id": 82,
    "track": "Reading Arabic",
    "category": "Light News",
    "level": "B1",
    "arabic": "سَجَّلَ الْمَعْرِضُ إِقْبَالًا كَبِيرًا",
    "transliteration": "Sajjala al-maʿriḍu iqbālan kabīran",
    "english": "The exhibition drew strong attendance",
    "answer": "the exhibition drew strong attendance",
    "notes": "Useful for reading headlines and short reports."
  },
  {
    "id": 83,
    "track": "Reading Arabic",
    "category": "Light News",
    "level": "B1",
    "arabic": "يَرَى كَثِيرُونَ أَنَّ الْفِكْرَةَ عَمَلِيَّةٌ",
    "transliteration": "Yarā kathīrūna anna al-fikrata ʿamaliyya",
    "english": "Many think the idea is practical",
    "answer": "many think the idea is practical",
    "notes": "Useful for reading headlines and short reports."
  },
  {
    "id": 84,
    "track": "Reading Arabic",
    "category": "Light News",
    "level": "B1",
    "arabic": "تَنَاوَلَ الْمَقَالُ قَضِيَّةً ثَقَافِيَّةً",
    "transliteration": "Tanāwala al-maqālu qaḍiyyatan thaqāfiyya",
    "english": "The article discussed a cultural issue",
    "answer": "the article discussed a cultural issue",
    "notes": "Useful for reading headlines and short reports."
  },
  {
    "id": 85,
    "track": "Reading Arabic",
    "category": "Light News",
    "level": "B1",
    "arabic": "سَيُعْقَدُ الِاجْتِمَاعُ فِي الْمَسَاءِ",
    "transliteration": "Sayuʿqadu al-ijtimāʿu fī al-masāʾ",
    "english": "The meeting will be held in the evening",
    "answer": "the meeting will be held in the evening",
    "notes": "Useful for reading headlines and short reports."
  },
  {
    "id": 86,
    "track": "Reading Arabic",
    "category": "Light News",
    "level": "B1",
    "arabic": "يُفَضِّلُ الْقُرَّاءُ النُّصُوصَ الْقَصِيرَةَ",
    "transliteration": "Yufaḍḍilu al-qurrāʾu an-nuṣūṣa al-qaṣīra",
    "english": "Readers prefer short texts",
    "answer": "readers prefer short texts",
    "notes": "Useful for reading headlines and short reports."
  },
  {
    "id": 87,
    "track": "Reading Arabic",
    "category": "Light News",
    "level": "B1",
    "arabic": "يَزْدَادُ اسْتِخْدَامُ الْهَوَاتِفِ فِي الْقِرَاءَةِ",
    "transliteration": "Yazdādu istikhdāmu al-hawātifi fī al-qirāʾa",
    "english": "The use of phones for reading is increasing",
    "answer": "the use of phones for reading is increasing",
    "notes": "Useful for reading headlines and short reports."
  },
  {
    "id": 88,
    "track": "Reading Arabic",
    "category": "Light News",
    "level": "B1",
    "arabic": "تُرَكِّزُ الدِّرَاسَةُ عَلَى السُّلُوكِ الْيَوْمِيِّ",
    "transliteration": "Turakkizu ad-dirāsatu ʿalā as-sulūki al-yawmī",
    "english": "The study focuses on daily behavior",
    "answer": "the study focuses on daily behavior",
    "notes": "Useful for reading headlines and short reports."
  },
  {
    "id": 89,
    "track": "Reading Arabic",
    "category": "Light News",
    "level": "B1",
    "arabic": "يُسَاعِدُ التَّكْرَارُ عَلَى تَثْبِيتِ الْمَعْلُومَةِ",
    "transliteration": "Yusāʿidu at-tikrāru ʿalā tathbīti al-maʿlūma",
    "english": "Repetition helps fix information in memory",
    "answer": "repetition helps fix information in memory",
    "notes": "Useful for reading headlines and short reports."
  },
  {
    "id": 90,
    "track": "History & Culture",
    "category": "History & Culture",
    "level": "B1",
    "arabic": "يَهْتَمُّ بِالتَّارِيخِ وَالْحَضَارَةِ",
    "transliteration": "Yahtammu bi-t-tārīkh wa-l-ḥaḍāra",
    "english": "He is interested in history and civilization",
    "answer": "he is interested in history and civilization",
    "notes": "Good for thoughtful reading practice."
  },
  {
    "id": 91,
    "track": "History & Culture",
    "category": "History & Culture",
    "level": "B1",
    "arabic": "تُعَدُّ الْمَكْتَبَةُ مَكَانًا لِلتَّأَمُّلِ",
    "transliteration": "Tuʿaddu al-maktabatu makānan li-t-taʾammul",
    "english": "The library is a place for reflection",
    "answer": "the library is a place for reflection",
    "notes": "Good for thoughtful reading practice."
  },
  {
    "id": 92,
    "track": "History & Culture",
    "category": "History & Culture",
    "level": "B1",
    "arabic": "تَحْمِلُ الْمُدُنُ الْقَدِيمَةُ ذَاكِرَةً طَوِيلَةً",
    "transliteration": "Taḥmilu al-mudunu al-qadīmatu dhākiratan ṭawīla",
    "english": "Old cities carry a long memory",
    "answer": "old cities carry a long memory",
    "notes": "Good for thoughtful reading practice."
  },
  {
    "id": 93,
    "track": "History & Culture",
    "category": "History & Culture",
    "level": "B1",
    "arabic": "يَكْشِفُ التَّارِيخُ أَشْكَالًا مُخْتَلِفَةً مِنَ التَّغْيِيرِ",
    "transliteration": "Yakshifu at-tārīkhu ashkālan mukhtalifatan mina at-taghyīr",
    "english": "History reveals different forms of change",
    "answer": "history reveals different forms of change",
    "notes": "Good for thoughtful reading practice."
  },
  {
    "id": 94,
    "track": "History & Culture",
    "category": "History & Culture",
    "level": "B1",
    "arabic": "تَرْبِطُ اللُّغَةُ بَيْنَ الْمَاضِي وَالْحَاضِرِ",
    "transliteration": "Tarbīṭu al-lughatu bayna al-māḍī wa-l-ḥāḍir",
    "english": "Language connects the past and the present",
    "answer": "language connects the past and the present",
    "notes": "Good for thoughtful reading practice."
  },
  {
    "id": 95,
    "track": "History & Culture",
    "category": "History & Culture",
    "level": "B1",
    "arabic": "تُسَاعِدُنَا الْقِرَاءَةُ عَلَى فَهْمِ الثَّقَافَاتِ",
    "transliteration": "Tusāʿidunā al-qirāʾatu ʿalā fahmi ath-thaqāfāt",
    "english": "Reading helps us understand cultures",
    "answer": "reading helps us understand cultures",
    "notes": "Good for thoughtful reading practice."
  },
  {
    "id": 96,
    "track": "History & Culture",
    "category": "History & Culture",
    "level": "B1",
    "arabic": "لِكُلِّ مَدِينَةٍ طَابِعُهَا الْخَاصُّ",
    "transliteration": "Li-kulli madīnatin ṭābiʿuhā al-khāṣṣ",
    "english": "Every city has its own character",
    "answer": "every city has its own character",
    "notes": "Good for thoughtful reading practice."
  },
  {
    "id": 97,
    "track": "History & Culture",
    "category": "History & Culture",
    "level": "B1",
    "arabic": "يَجْذِبُنِي التَّرَاثُ الْمِعْمَارِيُّ",
    "transliteration": "Yajdhibunī at-turāthu al-miʿmārī",
    "english": "Architectural heritage attracts me",
    "answer": "architectural heritage attracts me",
    "notes": "Good for thoughtful reading practice."
  },
  {
    "id": 98,
    "track": "History & Culture",
    "category": "History & Culture",
    "level": "B1",
    "arabic": "تَكْشِفُ الْأَسْوَاقُ الْقَدِيمَةُ كَثِيرًا مِنَ الْحَيَاةِ",
    "transliteration": "Takshifu al-aswāqu al-qadīmatu kathīran mina al-ḥayāh",
    "english": "Old markets reveal much about life",
    "answer": "old markets reveal much about life",
    "notes": "Good for thoughtful reading practice."
  },
  {
    "id": 99,
    "track": "History & Culture",
    "category": "History & Culture",
    "level": "B1",
    "arabic": "يَحْتَاجُ فَهْمُ النُّصُوصِ إِلَى صَبْرٍ",
    "transliteration": "Yaḥtāju fahmu an-nuṣūṣi ilā ṣabr",
    "english": "Understanding texts requires patience",
    "answer": "understanding texts requires patience",
    "notes": "Good for thoughtful reading practice."
  },
  {
    "id": 100,
    "track": "History & Culture",
    "category": "History & Culture",
    "level": "B1",
    "arabic": "كَثِيرٌ مِنَ الْأَفْكَارِ الْكَبِيرَةِ تَبْدَأُ بِسُؤَالٍ",
    "transliteration": "Kathīrun mina al-afkāri al-kabīra tabdaʾu bisuʾāl",
    "english": "Many big ideas begin with a question",
    "answer": "many big ideas begin with a question",
    "notes": "Good for thoughtful reading practice."
  },
  {
    "id": 101,
    "track": "History & Culture",
    "category": "History & Culture",
    "level": "B1",
    "arabic": "تُقَدِّمُ الرِّحْلَاتُ دُرُوسًا فِي الْمُقَارَنَةِ",
    "transliteration": "Tuqaddimu ar-riḥlātu durūsan fī al-muqārana",
    "english": "Journeys offer lessons in comparison",
    "answer": "journeys offer lessons in comparison",
    "notes": "Good for thoughtful reading practice."
  },
  {
    "id": 102,
    "track": "Culture & Proverbs",
    "category": "Proverbs",
    "level": "B1",
    "arabic": "مَنْ جَدَّ وَجَدَ",
    "transliteration": "Man jadda wajada",
    "english": "Who strives finds",
    "answer": "who strives finds",
    "notes": "Traditional saying worth remembering."
  },
  {
    "id": 103,
    "track": "Culture & Proverbs",
    "category": "Proverbs",
    "level": "B1",
    "arabic": "فِي التَّأَنِّي السَّلَامَةُ",
    "transliteration": "Fī at-taʾannī as-salāma",
    "english": "In patience there is safety",
    "answer": "in patience there is safety",
    "notes": "Traditional saying worth remembering."
  },
  {
    "id": 104,
    "track": "Culture & Proverbs",
    "category": "Proverbs",
    "level": "B1",
    "arabic": "خَيْرُ الْكَلَامِ مَا قَلَّ وَدَلَّ",
    "transliteration": "Khayru al-kalāmi mā qalla wa dalla",
    "english": "The best speech is brief and meaningful",
    "answer": "the best speech is brief and meaningful",
    "notes": "Traditional saying worth remembering."
  },
  {
    "id": 105,
    "track": "Culture & Proverbs",
    "category": "Proverbs",
    "level": "B1",
    "arabic": "لِكُلِّ مَقَامٍ مَقَالٌ",
    "transliteration": "Li-kulli maqāmin maqāl",
    "english": "Every situation has fitting words",
    "answer": "every situation has fitting words",
    "notes": "Traditional saying worth remembering."
  },
  {
    "id": 106,
    "track": "Culture & Proverbs",
    "category": "Proverbs",
    "level": "B1",
    "arabic": "الْعِلْمُ نُورٌ",
    "transliteration": "Al-ʿilmu nūr",
    "english": "Knowledge is light",
    "answer": "knowledge is light",
    "notes": "Traditional saying worth remembering."
  },
  {
    "id": 107,
    "track": "Culture & Proverbs",
    "category": "Proverbs",
    "level": "B1",
    "arabic": "الْكِتَابُ خَيْرُ جَلِيسٍ",
    "transliteration": "Al-kitābu khayru jalīs",
    "english": "A book is the best companion",
    "answer": "a book is the best companion",
    "notes": "Traditional saying worth remembering."
  },
  {
    "id": 108,
    "track": "Culture & Proverbs",
    "category": "Proverbs",
    "level": "B1",
    "arabic": "الصِّدْقُ نَجَاةٌ",
    "transliteration": "Aṣ-ṣidqu najāh",
    "english": "Honesty is salvation",
    "answer": "honesty is salvation",
    "notes": "Traditional saying worth remembering."
  },
  {
    "id": 109,
    "track": "Culture & Proverbs",
    "category": "Proverbs",
    "level": "B1",
    "arabic": "مَنْ طَلَبَ الْعُلَا سَهِرَ اللَّيَالِيَ",
    "transliteration": "Man ṭalaba al-ʿulā sahira al-layālī",
    "english": "Who seeks excellence stays up nights",
    "answer": "who seeks excellence stays up nights",
    "notes": "Traditional saying worth remembering."
  },
  {
    "id": 110,
    "track": "Poetry & Reflection",
    "category": "Poetic Lines",
    "level": "B1",
    "arabic": "وَلِلصُّبْحِ فِي أُفُقِ الْقُلُوبِ بَرِيقٌ",
    "transliteration": "Wa liṣ-ṣubḥi fī ufuqi al-qulūbi barīq",
    "english": "Morning has a glow in the horizon of hearts",
    "answer": "morning has a glow in the horizon of hearts",
    "notes": "Gentle literary Arabic."
  },
  {
    "id": 111,
    "track": "Poetry & Reflection",
    "category": "Poetic Lines",
    "level": "B1",
    "arabic": "فِي السَّفَرِ يَنْكَشِفُ مَعْنَى الطَّرِيقِ",
    "transliteration": "Fī as-safari yankashifu maʿnā aṭ-ṭarīq",
    "english": "In travel the meaning of the road is revealed",
    "answer": "in travel the meaning of the road is revealed",
    "notes": "Gentle literary Arabic."
  },
  {
    "id": 112,
    "track": "Poetry & Reflection",
    "category": "Poetic Lines",
    "level": "B1",
    "arabic": "يَبْقَى الْكَلَامُ الْجَمِيلُ فِي الذَّاكِرَةِ",
    "transliteration": "Yabqā al-kalāmu al-jamīlu fī adh-dhākira",
    "english": "Beautiful words remain in memory",
    "answer": "beautiful words remain in memory",
    "notes": "Gentle literary Arabic."
  },
  {
    "id": 113,
    "track": "Poetry & Reflection",
    "category": "Poetic Lines",
    "level": "B1",
    "arabic": "لِلْمَدِينَةِ وَجْهٌ يَتَغَيَّرُ مَعَ الْمَسَاءِ",
    "transliteration": "Li-l-madīnati wajhun yataghayyaru maʿa al-masāʾ",
    "english": "The city has a face that changes with evening",
    "answer": "the city has a face that changes with evening",
    "notes": "Gentle literary Arabic."
  },
  {
    "id": 114,
    "track": "Poetry & Reflection",
    "category": "Poetic Lines",
    "level": "B1",
    "arabic": "تُعَلِّمُنَا الْأَيَّامُ مَا لَا يُقَالُ مُبَاشَرَةً",
    "transliteration": "Tuʿallimunā al-ayyāmu mā lā yuqālu mubāsharatan",
    "english": "Days teach us what is not said directly",
    "answer": "days teach us what is not said directly",
    "notes": "Gentle literary Arabic."
  },
  {
    "id": 115,
    "track": "Poetry & Reflection",
    "category": "Poetic Lines",
    "level": "B1",
    "arabic": "بَيْنَ الصَّمْتِ وَالْكَلَامِ مَعْنًى آخَرُ",
    "transliteration": "Bayna aṣ-ṣamti wa-l-kalāmi maʿnan ākhar",
    "english": "Between silence and speech there is another meaning",
    "answer": "between silence and speech there is another meaning",
    "notes": "Gentle literary Arabic."
  },
  {
    "id": 116,
    "track": "Poetry & Reflection",
    "category": "Poetic Lines",
    "level": "B1",
    "arabic": "يَحْمِلُ الْبَحْرُ أَخْبَارَ الْمُدُنِ الْبَعِيدَةِ",
    "transliteration": "Yaḥmilu al-baḥru akhbāra al-muduni al-baʿīda",
    "english": "The sea carries news of distant cities",
    "answer": "the sea carries news of distant cities",
    "notes": "Gentle literary Arabic."
  },
  {
    "id": 117,
    "track": "Poetry & Reflection",
    "category": "Poetic Lines",
    "level": "B1",
    "arabic": "كُلُّ قِرَاءَةٍ تَفْتَحُ بَابًا جَدِيدًا",
    "transliteration": "Kullu qirāʾatin taftaḥu bāban jadīdan",
    "english": "Every reading opens a new door",
    "answer": "every reading opens a new door",
    "notes": "Gentle literary Arabic."
  },
  {
    "id": 118,
    "track": "Reading Arabic",
    "category": "Learning About Learning",
    "level": "B1",
    "arabic": "أَقْضِي نِصْفَ سَاعَةٍ فِي الْقِرَاءَةِ صَبَاحًا",
    "transliteration": "Aqḍī niṣfa sāʿatin fī al-qirāʾa ṣabāḥan",
    "english": "I spend half an hour reading in the morning",
    "answer": "i spend half an hour reading in the morning",
    "notes": "Useful metalinguistic sentence."
  },
  {
    "id": 119,
    "track": "Reading Arabic",
    "category": "Learning About Learning",
    "level": "B1",
    "arabic": "أُفَكِّرُ فِي مَعْنَى هَذِهِ الْجُمْلَةِ",
    "transliteration": "Ufakkiru fī maʿnā hādhihi al-jumla",
    "english": "I think about the meaning of this sentence",
    "answer": "i think about the meaning of this sentence",
    "notes": "Useful metalinguistic sentence."
  },
  {
    "id": 120,
    "track": "Reading Arabic",
    "category": "Learning About Learning",
    "level": "B1",
    "arabic": "هَذَا التَّعْبِيرُ شَائِعٌ فِي اللُّغَةِ الْحَدِيثَةِ",
    "transliteration": "Hādhā at-taʿbīru shāʾiʿun fī al-lughati al-ḥadītha",
    "english": "This expression is common in modern language",
    "answer": "this expression is common in modern language",
    "notes": "Useful metalinguistic sentence."
  },
  {
    "id": 121,
    "track": "Reading Arabic",
    "category": "Learning About Learning",
    "level": "B1",
    "arabic": "هَذِهِ الْكَلِمَةُ أَقْرَبُ إِلَى الْأُسْلُوبِ الرَّسْمِيِّ",
    "transliteration": "Hādhihi al-kalimatu aqrabu ilā al-uslūbi ar-rasmī",
    "english": "This word is closer to formal style",
    "answer": "this word is closer to formal style",
    "notes": "Useful metalinguistic sentence."
  },
  {
    "id": 122,
    "track": "Reading Arabic",
    "category": "Learning About Learning",
    "level": "B1",
    "arabic": "يَسْهُلُ تَذَكُّرُ الْكَلِمَاتِ عِنْدَمَا تَأْتِي فِي جُمْلَةٍ",
    "transliteration": "Yashulu tadhakkuru al-kalimāti ʿindamā taʾtī fī jumla",
    "english": "Words are easier to remember when they come in a sentence",
    "answer": "words are easier to remember when they come in a sentence",
    "notes": "Useful metalinguistic sentence."
  },
  {
    "id": 123,
    "track": "Reading Arabic",
    "category": "Learning About Learning",
    "level": "B1",
    "arabic": "أُفَضِّلُ الْجُمَلَ الْقَصِيرَةَ فِي الْبِدَايَةِ",
    "transliteration": "Ufaḍḍilu al-jumala al-qaṣīra fī al-bidāya",
    "english": "I prefer short sentences in the beginning",
    "answer": "i prefer short sentences in the beginning",
    "notes": "Useful metalinguistic sentence."
  },
  {
    "id": 124,
    "track": "Reading Arabic",
    "category": "Learning About Learning",
    "level": "B1",
    "arabic": "ثُمَّ أَنْتَقِلُ إِلَى نُصُوصٍ أَطْوَلَ",
    "transliteration": "Thumma أنتَقِلُ إِلَى نُصُوصٍ أَطْوَلَ",
    "english": "Then I move to longer texts",
    "answer": "then i move to longer texts",
    "notes": "Useful metalinguistic sentence."
  },
  {
    "id": 125,
    "track": "Reading Arabic",
    "category": "Learning About Learning",
    "level": "B1",
    "arabic": "لَا أُرِيدُ دَرْسًا طَوِيلًا جِدًّا",
    "transliteration": "Lā urīdu darsan ṭawīlan jiddan",
    "english": "I do not want a very long lesson",
    "answer": "i do not want a very long lesson",
    "notes": "Useful metalinguistic sentence."
  },
  {
    "id": 126,
    "track": "Reading Arabic",
    "category": "Learning About Learning",
    "level": "B1",
    "arabic": "بَعْدَ أَنْ يَنْتَهِي الدَّرْسُ أَتَوَقَّفُ",
    "transliteration": "Baʿda an yantahī ad-darsu atawaqqaf",
    "english": "After the lesson ends, I stop",
    "answer": "after the lesson ends, i stop",
    "notes": "Useful metalinguistic sentence."
  },
  {
    "id": 127,
    "track": "Reading Arabic",
    "category": "Learning About Learning",
    "level": "B1",
    "arabic": "أُحِبُّ التَّنَوُّعَ فِي الْمَوَاضِيعِ",
    "transliteration": "Uḥibbu at-tanawwuʿa fī al-mawāḍīʿ",
    "english": "I like variety in topics",
    "answer": "i like variety in topics",
    "notes": "Useful metalinguistic sentence."
  },
  {
    "id": 128,
    "track": "Reading Arabic",
    "category": "Learning About Learning",
    "level": "B1",
    "arabic": "تُسَاعِدُنِي الْعِبَارَاتُ الْجَدِيدَةُ عَلَى الْمُوَاصَلَةِ",
    "transliteration": "Tusāʿidunī al-ʿibārātu al-jadīda ʿalā al-muwāṣala",
    "english": "New phrases help me continue",
    "answer": "new phrases help me continue",
    "notes": "Useful metalinguistic sentence."
  },
  {
    "id": 129,
    "track": "Reading Arabic",
    "category": "Learning About Learning",
    "level": "B1",
    "arabic": "الْمُهِمُّ أَلَّا يَكُونَ هُنَاكَ تَكْرَارٌ كَثِيرٌ",
    "transliteration": "Al-muhimmu allā yakūna hunāka tikrārun kathīr",
    "english": "What matters is that there is not too much repetition",
    "answer": "what matters is that there is not too much repetition",
    "notes": "Useful metalinguistic sentence."
  }
];
